// is hidden
user_pref("ghacks_user.js.parrot", "0100 syntax error: the parrot's dead!");
user_pref("browser.slowStartup.notificationDisabled", true);
user_pref("browser.slowStartup.maxSamples", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("startup.homepage_welcome_url", "");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("startup.homepage_override_url", "");
user_pref("browser.laterrun.enabled", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.usedOnWindows10.introURL", "");
user_pref("ghacks_user.js.parrot", "0200 syntax error: the parrot's definitely deceased!");
user_pref("geo.enabled", false);
user_pref("geo.wifi.uri", "https://127.0.0.1");
user_pref("geo.wifi.logging.enabled", false); //
user_pref("browser.search.geoip.url", "");
user_pref("geo.wifi.xhr.timeout", 1);
user_pref("browser.search.geoip.timeout", 1);
user_pref("browser.search.countryCode", "US"); //
user_pref("browser.search.region", "US"); //
user_pref("intl.locale.matchOS", false);
user_pref("general.useragent.locale", "en-US");
user_pref("browser.search.geoSpecificDefaults", false);
user_pref("browser.search.geoSpecificDefaults.url", "");
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true); //
user_pref("ghacks_user.js.parrot", "0300 syntax error: the parrot's not pinin' for the fjords!");
user_pref("app.update.enabled", false);
user_pref("app.update.service.enabled", false);
user_pref("app.update.silent", false);
user_pref("app.update.staging.enabled", false);
user_pref("app.update.auto", false);
user_pref("browser.search.update", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("lightweightThemes.update.enabled", false);
user_pref("dom.ipc.plugins.flash.subprocess.crashreporter.enabled", false);
user_pref("dom.ipc.plugins.reportCrashURL", false);
user_pref("extensions.webservice.discoverURL", "http://127.0.0.1");
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unifiedIsOptIn", true); //
user_pref("toolkit.telemetry.server", "");
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.healthreport.documentServerURI", ""); //
user_pref("datareporting.healthreport.service.enabled", false); //
user_pref("datareporting.healthreport.about.reportUrl", "data:text/plain,");
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("toolkit.telemetry.cachedClientID", "");
user_pref("browser.selfsupport.enabled", false); //
user_pref("browser.selfsupport.url", "");
user_pref("experiments.enabled", false);
user_pref("experiments.manifest.uri", "");
user_pref("experiments.supported", false);
user_pref("experiments.activeExperiment", false);
user_pref("network.allow-experiments", false);
user_pref("breakpad.reportURL", "");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.newtab.preload", false);
user_pref("browser.newtabpage.directory.ping", "data:text/plain,");
user_pref("browser.newtabpage.directory.source", "data:text/plain,");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.aboutHomeSnippets.updateUrl", "https://127.0.0.1");
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.pocket.api", "");
user_pref("extensions.pocket.site", "");
user_pref("extensions.pocket.oAuthConsumerKey", "");
user_pref("social.whitelist", "");
user_pref("social.toast-notifications.enabled", false);
user_pref("social.shareDirectory", "");
user_pref("social.remote-install.enabled", false);
user_pref("social.directories", "");
user_pref("social.share.activationPanelEnabled", false);
user_pref("social.enabled", false); //
user_pref("reader.parse-on-load.enabled", false);
user_pref("dom.flyweb.enabled", false);
user_pref("services.sync.enabled", false); //
user_pref("ghacks_user.js.parrot", "0400 syntax error: the parrot's passed on!");
user_pref("extensions.blocklist.enabled", true);
user_pref("extensions.blocklist.url", "https://blocklist.addons.mozilla.org/blocklist/3/%APP_ID%/%APP_VERSION%/");
user_pref("services.blocklist.update_enabled", true);
user_pref("services.blocklist.signing.enforced", true);
user_pref("services.blocklist.onecrl.collection", "certificates");
user_pref("services.blocklist.addons.collection", "addons");
user_pref("services.blocklist.plugins.collection", "");
user_pref("services.blocklist.gfx.collection", "");
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.block_dangerous", false);
user_pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);
user_pref("browser.safebrowsing.provider.google.updateURL", "");
user_pref("browser.safebrowsing.provider.google.gethashURL", "");
user_pref("browser.safebrowsing.provider.google4.updateURL", "");
user_pref("browser.safebrowsing.provider.google4.gethashURL", "");
user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.provider.google.reportURL", "");
user_pref("browser.safebrowsing.reportMalwareMistakeURL", "");
user_pref("browser.safebrowsing.reportPhishMistakeURL", "");
user_pref("browser.safebrowsing.reportPhishURL", "");
user_pref("browser.safebrowsing.provider.google4.reportURL", "");
user_pref("privacy.trackingprotection.enabled", false);
user_pref("privacy.trackingprotection.pbmode.enabled", false);
user_pref("privacy.trackingprotection.ui.enabled", true);
user_pref("security.ssl.errorReporting.automatic", false);
user_pref("security.ssl.errorReporting.enabled", false);
user_pref("security.ssl.errorReporting.url", "");
user_pref("browser.safebrowsing.blockedURIs.enabled", false);
user_pref("ghacks_user.js.parrot", "0600 syntax error: the parrot's no more!");
user_pref("network.prefetch-next", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.dns.disablePrefetchFromHTTPS", true); //
user_pref("network.predictor.enabled", false);
user_pref("captivedetect.canonicalURL", "");
user_pref("network.captive-portal-service.enabled", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("browser.send_pings", false);
user_pref("browser.send_pings.require_same_host", true);
user_pref("network.protocol-handler.external.ms-windows-store", false);
user_pref("network.predictor.enable-prefetch", false);
user_pref("ghacks_user.js.parrot", "0800 syntax error: the parrot's ceased to be!");
user_pref("keyword.enabled", false);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("browser.urlbar.maxRichResults", 0);
user_pref("browser.urlbar.trimURLs", false);
user_pref("browser.urlbar.autoFill", false);
user_pref("browser.urlbar.autoFill.typed", false);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.sessionhistory.max_entries", 4);
user_pref("layout.css.visited_links_enabled", false);
user_pref("browser.urlbar.filter.javascript", true);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("browser.urlbar.userMadeSearchSuggestionsChoice", true);
user_pref("browser.taskbar.lists.enabled", false);
user_pref("browser.taskbar.lists.frequent.enabled", false);
user_pref("browser.taskbar.lists.recent.enabled", false);
user_pref("browser.taskbar.lists.tasks.enabled", false);
user_pref("browser.taskbar.previews.enable", false);
user_pref("browser.urlbar.oneOffSearches", false);
user_pref("browser.search.reset.enabled", false);
user_pref("browser.search.reset.whitelist", "");
user_pref("ghacks_user.js.parrot", "0900 syntax error: the parrot's expired!");
user_pref("security.ask_for_password", 2);
user_pref("security.password_lifetime", 5);
user_pref("signon.autofillForms", false);
user_pref("signon.storeWhenAutocompleteOff", true);
user_pref("security.insecure_password.ui.enabled", true);
user_pref("browser.fixup.hide_user_pass", true);
user_pref("signon.formlessCapture.enabled", false);
user_pref("ghacks_user.js.parrot", "1000 syntax error: the parrot's gone to meet 'is maker!");
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk_cache_ssl", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.sessionstore.privacy_level", 2);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
user_pref("browser.cache.frecency_experiment", -1);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("ghacks_user.js.parrot", "1200 syntax error: the parrot's a stiff!");
user_pref("security.tls.unrestricted_rc4_fallback", false);
user_pref("security.ssl.enable_ocsp_stapling", true);
user_pref("security.ssl.treat_unsafe_negotiation_as_broken", true);
user_pref("security.OCSP.enabled", 1);
user_pref("security.cert_pinning.enforcement_level", 2);
user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);
user_pref("security.pki.sha1_enforcement_level", 1);
user_pref("security.ssl.disable_session_identifiers", true); //
user_pref("security.ssl3.rsa_des_ede3_sha", false);
user_pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
user_pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
user_pref("security.family_safety.mode", 0);
user_pref("security.mixed_content.block_active_content", true);
user_pref("security.mixed_content.send_hsts_priming", false);
user_pref("security.mixed_content.use_hsts", false);
user_pref("browser.ssl_override_behavior", 1);
user_pref("ghacks_user.js.parrot", "1400 syntax error: the parrot's bereft of life!");
user_pref("browser.display.use_document_fonts", 0);
user_pref("gfx.downloadable_fonts.enabled", true);
user_pref("gfx.font_rendering.opentype_svg.enabled", false);
user_pref("font.name.serif.x-unicode", "Georgia");
user_pref("font.name.serif.x-western", "Georgia");
user_pref("font.name.sans-serif.x-unicode", "Arial");
user_pref("font.name.sans-serif.x-western", "Arial");
user_pref("font.name.monospace.x-unicode", "Lucida Console");
user_pref("font.name.monospace.x-western", "Lucida Console");
user_pref("gfx.downloadable_fonts.woff2.enabled", false);
user_pref("layout.css.font-loading-api.enabled", false);
user_pref("font.blacklist.underline_offset", "");
user_pref("gfx.font_rendering.graphite.enabled", false);
user_pref("ghacks_user.js.parrot", "1600 syntax error: the parrot rests in peace!");
user_pref("network.http.sendSecureXSiteReferrer", false);
user_pref("ghacks_user.js.parrot", "1800 syntax error: the parrot's pushing up daisies!");
user_pref("plugin.default.state", 0);
user_pref("plugin.defaultXpi.state", 0);
user_pref("plugins.click_to_play", true);
user_pref("plugin.sessionPermissionNow.intervalInMinutes", 0);
user_pref("security.xpconnect.plugin.unrestricted", false);
user_pref("plugin.scan.plid.all", false);
user_pref("plugin.scan.Acrobat", "99999");
user_pref("plugin.scan.Quicktime", "99999");
user_pref("plugin.scan.WindowsMediaPlayer", "99999");
user_pref("media.autoplay.enabled", false);
user_pref("media.block-autoplay-until-in-foreground", true);
user_pref("media.gmp-provider.enabled", false);
user_pref("media.gmp.trial-create.enabled", false);
user_pref("media.gmp-widevinecdm.visible", false);
user_pref("media.gmp-widevinecdm.enabled", false);
user_pref("media.gmp-widevinecdm.autoupdate", false);
user_pref("media.eme.enabled", false);
user_pref("browser.eme.ui.enabled", false);
user_pref("media.eme.apiVisible", false);
user_pref("media.gmp-gmpopenh264.enabled", false); //
user_pref("media.gmp-gmpopenh264.autoupdate", false);
user_pref("media.gmp-manager.url", "data:text/plain,");
user_pref("media.gmp-eme-adobe.enabled", false);
user_pref("media.gmp-eme-adobe.visible", false);
user_pref("media.gmp-eme-adobe.autoupdate", false);
user_pref("ghacks_user.js.parrot", "2000 syntax error: the parrot's snuffed it!");
user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.use_document_iceservers", false);
user_pref("media.peerconnection.video.enabled", false);
user_pref("media.peerconnection.identity.enabled", false);
user_pref("media.peerconnection.identity.timeout", 1);
user_pref("media.peerconnection.turn.disable", true);
user_pref("media.navigator.video.enabled", false);
user_pref("media.peerconnection.ice.default_address_only", true);
user_pref("media.peerconnection.ice.no_host", true);
user_pref("webgl.disabled", true);
user_pref("pdfjs.enableWebGL", false);
user_pref("webgl.min_capability_mode", true);
user_pref("webgl.disable-extensions", true);
user_pref("webgl.disable-fail-if-major-performance-caveat", true);
user_pref("webgl.enable-debug-renderer-info", false);
user_pref("webgl.dxgl.enabled", false);
user_pref("webgl.enable-webgl2", false);
user_pref("media.webspeech.recognition.enable", false);
user_pref("media.webspeech.synth.enabled", false);
user_pref("media.getusermedia.screensharing.enabled", false);
user_pref("media.getusermedia.screensharing.allowed_domains", "");
user_pref("media.getusermedia.screensharing.allow_on_old_platforms", false);
user_pref("media.getusermedia.browser.enabled", false);
user_pref("media.getusermedia.audiocapture.enabled", false);
user_pref("camera.control.face_detection.enabled", false);
user_pref("media.mediasource.enabled", true);
user_pref("media.mediasource.mp4.enabled", true);
user_pref("media.mediasource.webm.audio.enabled", true);
user_pref("media.mediasource.webm.enabled", true);
user_pref("media.mp4.enabled", true);
user_pref("media.flac.enabled", true);
user_pref("media.ogg.enabled", false);
user_pref("media.ogg.flac.enabled", false);
user_pref("media.opus.enabled", false);
user_pref("media.raw.enabled", false);
user_pref("media.wave.enabled", false);
user_pref("media.webm.enabled", true);
user_pref("media.wmf.enabled", true);
user_pref("canvas.capturestream.enabled", false);
user_pref("dom.imagecapture.enabled", false);
user_pref("gfx.offscreencanvas.enabled", false);
user_pref("ghacks_user.js.parrot", "2200 syntax error: the parrot's 'istory!");
user_pref("dom.event.contextmenu.enabled", false);
user_pref("dom.disable_window_open_feature.location", true);
user_pref("dom.disable_window_open_feature.menubar", true);
user_pref("dom.disable_window_open_feature.resizable", true);
user_pref("dom.disable_window_open_feature.status", true);
user_pref("dom.disable_window_open_feature.toolbar", true);
user_pref("dom.disable_window_flip", true);
user_pref("dom.disable_window_move_resize", true);
user_pref("dom.disable_window_open_feature.close", true);
user_pref("dom.disable_window_open_feature.minimizable", true);
user_pref("dom.disable_window_open_feature.personalbar", true);
user_pref("dom.disable_window_open_feature.titlebar", true);
user_pref("dom.disable_window_status_change", true);
user_pref("dom.allow_scripts_to_close_windows", false);
user_pref("dom.disable_beforeunload", true);
user_pref("ghacks_user.js.parrot", "2300 syntax error: the parrot's off the twig!");
user_pref("dom.workers.enabled", false);
user_pref("dom.serviceWorkers.enabled", false);
user_pref("dom.caches.enabled", false);
user_pref("dom.push.enabled", false);
user_pref("dom.push.connection.enabled", false);
user_pref("dom.push.serverURL", "");
user_pref("dom.push.userAgentID", "");
user_pref("dom.webnotifications.enabled", false);
user_pref("dom.webnotifications.serviceworker.enabled", false);
user_pref("ghacks_user.js.parrot", "2400 syntax error: the parrot's kicked the bucket!");
user_pref("dom.event.clipboardevents.enabled", false);
user_pref("dom.allow_cut_copy", false); //
user_pref("dom.indexedDB.enabled", false);
user_pref("dom.telephony.enabled", false);
user_pref("dom.enable_user_timing", false);
user_pref("dom.enable_resource_timing", false);
user_pref("dom.enable_performance", false);
user_pref("dom.vibrator.enabled", false);
user_pref("dom.popup_maximum", 3);
user_pref("dom.popup_allowed_events", "click dblclick");
user_pref("dom.idle-observers-api.enabled", false);
user_pref("full-screen-api.enabled", false);
user_pref("javascript.options.asmjs", false);
user_pref("dom.archivereader.enabled", false);
user_pref("offline-apps.allow_by_default", false);
user_pref("browser.offline-apps.notify", true);
user_pref("ghacks_user.js.parrot", "2500 syntax error: the parrot's shuffled off 'is mortal coil!");
user_pref("dom.gamepad.enabled", false);
user_pref("dom.battery.enabled", false);
user_pref("dom.netinfo.enabled", false);
user_pref("dom.vr.enabled", false);
user_pref("dom.vr.oculus.enabled", false);
user_pref("dom.vr.osvr.enabled", false);
user_pref("dom.vr.openvr.enabled", false);
user_pref("media.navigator.enabled", false);
user_pref("media.video_stats.enabled", false);
user_pref("dom.keyboardevent.code.enabled", false);
user_pref("dom.beforeAfterKeyboardEvent.enabled", false);
user_pref("dom.keyboardevent.dispatch_during_composition", false);
user_pref("gfx.direct2d.disabled", true);
user_pref("layers.acceleration.disabled", true);
user_pref("dom.w3c_touch_events.enabled", 0);
user_pref("dom.webaudio.enabled", false);
user_pref("media.ondevicechange.enabled", false);
user_pref("ghacks_user.js.parrot", "2600 syntax error: the parrot's run down the curtain!");
user_pref("beacon.enabled", false);
user_pref("browser.download.folderList", 2);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.helperApps.deleteTempFileOnExit", true);
user_pref("browser.download.manager.addToRecentDocs", false);
user_pref("browser.download.hide_plugins_without_extensions", false);
user_pref("browser.pagethumbnails.capturing_disabled", true);
user_pref("network.jar.open-unsafe-types", false);
user_pref("devtools.webide.autoinstallADBHelper", false);
user_pref("devtools.webide.autoinstallFxdtAdapters", false);
user_pref("devtools.debugger.remote-enabled", false);
user_pref("devtools.webide.enabled", false);
user_pref("browser.casting.enabled", false);
user_pref("gfx.layerscope.enabled", false);
user_pref("device.sensors.enabled", false);
user_pref("network.http.spdy.enabled", false);
user_pref("network.http.spdy.enabled.deps", false);
user_pref("network.http.spdy.enabled.http2", false);
user_pref("pdfjs.disabled", false);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.http.redirection-limit", 10);
user_pref("middlemouse.contentLoadURL", false);
user_pref("security.dialog_enable_delay", 1000);
user_pref("security.fileuri.strict_origin_policy", true);
user_pref("security.sri.enable", true);
user_pref("network.dns.blockDotOnion", true);
user_pref("general.useragent.compatMode.firefox", false);
user_pref("general.buildID.override", "20100101"); //
user_pref("general.appname.override", "Netscape"); //
user_pref("general.appversion.override", "5.0 (Windows)"); //
user_pref("general.platform.override", "Win32"); //
user_pref("general.oscpu.override", "Windows NT 6.1"); //
user_pref("browser.uitour.enabled", false);
user_pref("browser.uitour.url", "");
user_pref("network.jar.block-remote-files", true);
user_pref("dom.ipc.shims.enabledWarnings", true);
user_pref("browser.tabs.remote.separateFileUriProcess", true);
user_pref("browser.download.forbid_open_with", true);
user_pref("mathml.disabled", true);
user_pref("device.storage.enabled", false);
user_pref("webchannel.allowObject.urlWhitelist", "");
user_pref("network.http.altsvc.enabled", false);
user_pref("network.http.altsvc.oe", false);
user_pref("devtools.chrome.enabled", false);
user_pref("extensions.enabledScopes", 1); //
user_pref("extensions.autoDisableScopes", 15);
user_pref("network.proxy.autoconfig_url.include_path", false);
user_pref("security.block_script_with_wrong_mime", true);
user_pref("svg.disabled", true);
user_pref("network.IDN_show_punycode", true);
user_pref("privacy.resistFingerprinting", true); //
user_pref("ghacks_user.js.parrot", "2700 syntax error: the parrot's joined the bleedin' choir invisible!");
user_pref("network.cookie.cookieBehavior", 2);
user_pref("network.cookie.thirdparty.sessionOnly", true);
user_pref("dom.storageManager.enabled", false);
user_pref("extensions.webextensions.keepStorageOnUninstall", false);
user_pref("extensions.webextensions.keepUuidOnUninstall", false);
user_pref("ghacks_user.js.parrot", "2800 syntax error: the parrot's bleedin' demised!");
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("privacy.clearOnShutdown.cache", true);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.clearOnShutdown.downloads", true);
user_pref("privacy.clearOnShutdown.formdata", true);
user_pref("privacy.clearOnShutdown.history", true);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.sessions", false);
user_pref("privacy.clearOnShutdown.siteSettings", false);
user_pref("privacy.cpd.cache", true);
user_pref("privacy.cpd.cookies", false);
user_pref("privacy.cpd.downloads", true);
user_pref("privacy.cpd.formdata", true);
user_pref("privacy.cpd.history", true);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.passwords", false);
user_pref("privacy.cpd.sessions", false);
user_pref("privacy.cpd.siteSettings", false);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("ghacks_user.js.parrot", "syntax error!");
user_pref("general.warnOnAboutConfig", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.backspace_action", 2);
user_pref("clipboard.autocopy", false);
user_pref("browser.link.open_newwindow", 3);
user_pref("browser.ctrlTab.previews", true);
user_pref("view_source.tab", false);
user_pref("layout.spellcheckDefault", 1);
user_pref("network.manage-offline-status", false);
user_pref("browser.tabs.animate", false);
user_pref("browser.fullscreen.animate", false);
user_pref("ui.submenuDelay", 75); //
user_pref("browser.bookmarks.max_backups", 2);
user_pref("browser.urlbar.clickSelectsAll", true);
user_pref("browser.urlbar.doubleClickSelectsAll", false);
user_pref("browser.tabs.insertRelatedAfterCurrent", true);
user_pref("browser.tabs.selectOwnerOnClose", true);
user_pref("browser.tabs.loadInBackground", true);
user_pref("browser.tabs.loadDivertedInBackground", false);
user_pref("browser.bookmarks.showRecentlyBookmarked", false);
user_pref("browser.migrate.automigrate.enabled", false);
user_pref("ghacks_user.js.parrot", "Not dead");
